- src/main/kotlin/no/nav/syfo/client/graphapi/AdRolle.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiClient.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiUserGroupsResponse.kt
- src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt
- src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
Will add test when we have enough functionality to make an integration test.
> Add GraphApi Client

- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/ClientsEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/azuread/AzureAdClient.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/AdRolle.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/AdRoller.kt
- src/main/kotlin/no/nav/syfo/tilgang/Tilgang.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/main/kotlin/no/nav/syfo/util/ObjectMapperConfig.kt
- src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt
- src/test/kotlin/no/nav/syfo/mocks/AzureAdMock.kt
- src/test/kotlin/no/nav/syfo/mocks/GraphApiMock.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/MockUtils.kt
- src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/JWTUtil.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangApiSpek.kt
- src/test/resources/jwkset.json
- src/test/resources/logback-test.xml
Add authentication
Add end to end tests
Try out MockEngine to see if it's quicker than starting Netty servers.
> Add tilgangTilTjenesten endpoint

- build.gradle.kts
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiClient.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiClientMetric.kt
Also upgrade ktlint, this fixes the local bug where deleted files are included in the lint checks
> Add metrics to graph api get user groups call

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/ClientsEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/graphapi/GraphApiClient.kt
- src/main/kotlin/no/nav/syfo/client/skjermedepersoner/SkjermedePersonerMetric.kt
- src/main/kotlin/no/nav/syfo/client/skjermedepersoner/SkjermedePersonerPipClient.kt
- src/main/kotlin/no/nav/syfo/client/skjermedepersoner/SkjermedePersonerRequestDTO.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/SkjermedePersonerMock.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangApiSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
New client (PR for access: https://github.com/navikt/skjerming/pull/312).
Add new method in TilgangService.
> Add check for access to skjermede personer

- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlClientMetric.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlError.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonResponse.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlRequest.kt
- src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
- src/main/resources/pdl/hentPerson.graphql
Get adressebeskyttelse from person endpoint.
> Add pdl client

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/ClientsEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Add to environment.
Add unused mockk in tests.
> Send PdlClient to TilgangService

- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
Also change personIdentNumber to personident
> Use obo token for call to pdl

- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/PdlMock.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
Get kode6 and kode7 from pdl and check veileders access if necessary
> Check adressebeskyttelse in tilgangservice

- src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/BehandlendeEnhetMock.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/PdlMock.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
Add mocking to keep existing tests happy, new tests in next PR
> Check veileders geografisk access

- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
Also fix mocks for all tests so only relevant functionality is tested
> Add tests for geografisk access check

- src/main/kotlin/no/nav/syfo/client/norg/NorgClient.kt
- src/main/kotlin/no/nav/syfo/client/norg/NorgClientMetric.kt
- src/main/kotlin/no/nav/syfo/client/norg/domain/NorgEnhet.kt
With method for getting overordnet enhet
> Add NorgClient

- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/test/kotlin/no/nav/syfo/mocks/AxsysMock.kt
- src/test/kotlin/no/nav/syfo/mocks/BehandlendeEnhetMock.kt
- src/test/kotlin/no/nav/syfo/mocks/GraphApiMock.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/MockUtils.kt
- src/test/kotlin/no/nav/syfo/mocks/NorgMock.kt
- src/test/kotlin/no/nav/syfo/mocks/PdlMock.kt
- src/test/kotlin/no/nav/syfo/mocks/SkjermedePersonerMock.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangApiSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Add tests for api, with updated mocks.
Now it will be possible to get correct access result for a given innbygger.
> Use hasTilgangToPerson in tilgangApi

- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Will be used by syfooversiktsrv to remove innbyggere the veileder doesn't have access to.
> Add endpoint for list of innbyggere

- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Auditlogger i service-metoden som gjør sjekk på tilgang til person. Dermed blir det auditlogget for alle api-kall som gjør tilgangssjekk (både /person og /brukere-endepunkt).
Fikset samtidig noen exception messages som ikke var helt riktige :broom:
> IS-1763: Audit log in checkTilgangToPerson

- src/main/kotlin/no/nav/syfo/client/pdl/PipPersondataResponse.kt
Det er har kommet en del feil i dev på at gtType er null. Ser ikke ut til at det forekommer i prod (ennå).
> IS-1804: Akseptere null verdi for gtType

- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/GraphApiMock.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangApiSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
This checks access to papirsykmelding group as well as ordinary person access.
Used by team sykmelding.
> IS-1852: Add endpoint for papirsykmelding

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Lagt til `lps-oppfolgingsplan-mottak` i accessPolicy-listen
Hva er nytt / hva har blitt fikset?
Gir `lps-oppfolgingsplan-mottak` mulighet til å kalle `istilgangskontroll` for å sjekke om
en veileder har tilgang til arbeidstaker ifm. å hente ut arbeidstakers Altinn-LPS planer i Modia.
> Add lps-oppfolgingsplan-mottak to access policies

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
> syfomotebehov migreres til GCP

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Vi har allokert mye mer ressurser enn vi bruker her, så reduserer det for å spare kostnader på GCP.
> Reduce resource allocation

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Gir `isarbeidsuforhet` tilgang til tilgang-api
> IS-2092: Add inbound rule for isarbeidsuforhet

- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
De som styrer med audit logging vil ikke at vi skal logge når det gjøres oppslag på lister av folk, siden det bare blir støy.
Gjør audit logging default, slik at vi ikke trenger å endre på andre metoder enn listesøket, og fordi det er bedre med opt out på dette.
> IS-2216: Don't audit log access to list of people

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- Får feil i nais console siden vi bare har outbound rule i `ismeroppfolging`, men mangler inbound rule her
> IS: Add inbound rule for ismeroppfolging

- src/main/kotlin/no/nav/syfo/tilgang/TilgangApi.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- Gjør tilgangssjekk parallellt i stedet for sekvensielt. Dette ser ut til å være ny flaskehals etter endringene gjort [her](https://trello.com/c/On3r4wFX/2465-minske-tiden-det-tar-%C3%A5-vise-oversikten-for-veileder)
> IS-2493: Do access check in parallell

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Slik at vi kan sjekke tilgang til person når veileder skal hente skjemasvar
> IS-2433: Inbound rule for meroppfolging-backend

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Slik at ny app med maksdato kan kalle tilgangskontrollen.
> IS: Add inbound rule for sykepengedager-informasjon

- build.gradle.kts
> IS-2534: Update dependencies

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
> IS-2641: service discovery norg2

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
gi aksess til ismanglendemedvirkning
> Gi aksess til ismanglendemedvirkning

- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Ser at det funker tilsynelatende bra, men det lages mange tråder i JVM'en. Tror det er bedre å instansiere dispatcher'en *en* gang, og ikke hver gang man trenger den.
> IS-2726: Instansiere dispatcher en gang og ikke hver gang

- .nais/redis/aiven-redis.yaml
Fikser liten syntaks-feil i yaml-fila
> IS-2756: Oppsett Redis-cache på Aiven

- .nais/naiserator-prod.yaml
Ble et deploy-problem med forrige PR, så må gi tilgang til den gamle cachen inntil videre.
> IS-2765: Bruke felles Aiven-cache

- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt
- src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt
- src/test/kotlin/no/nav/syfo/client/azuread/AzureAdClientSpek.kt
- src/test/kotlin/no/nav/syfo/client/graphapi/GraphApiClientSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangApiSpek.kt
> IS-2720: Ktor 3.0

- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Håndtere manglende enhet for en gitt innbygger (unngå at enhetens oversikt blir tom)
> IS-2988: Handle missing enhet

- src/main/kotlin/no/nav/syfo/client/norg/NorgClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
Veiledere ved fylkeskontor med regional tilgang (og syfo-tilgang) skal ha tilgang til innbyggere i fylkets kommuner.
> IS-3043: Bugfix veiledere ved fylkeskontor med regional tilgang

- .github/workflows/aiven-valkey.yaml
- .nais/valkey/aiven-valkey.yaml
- .nais/valkey/dev.json
- .nais/valkey/prod.json
Begynner med en PR som oppretter den nye Valkey-cachen som skal overta for Redis-cachen vi bruker nå.
> IS-3066: Definere Valkey-cache

- src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetClient.kt
- src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetDTO.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/BehandlendeEnhetMock.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Tilpasser til ny struktur på dto fra `syfobehandlendeenhet`.
> IS-3171: Update behandlendeenhet dto

- src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetClient.kt
Skrur på caching igjen (nå skal det ikke lengre ligger objekter på gammelt format i valkey-cachen)
> IS-3171: Skrur på caching av behandlendeenhet igjen

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/ClientsEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/tilgangsmaskin/TilgangsmaskinClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/MockClient.kt
- src/test/kotlin/no/nav/syfo/mocks/TilgangsmaskinMock.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServicePersonSpek.kt
- src/test/kotlin/no/nav/syfo/tilgang/TilgangServiceSpek.kt
Tester og teller om tilgangsmaskin gir samme resultat som vår egen logikk.
> IS-3291: Teste ut tilgangsmaskin

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
Sjekken mot `tilgangsmaskin `er "tråd-krevende", så skalerer opp litt. Ser at det har oppstått noen situasjoner der `syfooversiktsrv` ikke får svar - håper dette bedrer situasjonen.
> IS-3291: Øke antall tråder

- Dockerfile
- src/main/kotlin/no/nav/syfo/App.kt
Nytt forsøk på å løse problem med sporadiske timeouts
(hvis dette virker er det noe vi også bør gjøre i andre app'er)
> IS-3291: Set not ready in shutdown hook

- src/main/kotlin/no/nav/syfo/client/tilgangsmaskin/ProblemDetailResponse.kt
- src/main/kotlin/no/nav/syfo/client/tilgangsmaskin/TilgangsmaskinClient.kt
- src/main/kotlin/no/nav/syfo/tilgang/TilgangService.kt
- src/test/kotlin/no/nav/syfo/mocks/TilgangsmaskinMock.kt
For å kunne undersøke årsaken til ulikt resultat fra vår egen tilgangskontroll og tilgangsmaskin må vi logge veilederident og årsak.
> IS-3401: Forbedre logging når tilgangsmaskin gir annet resultat

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Removing access for removed syfomotebehov in fss
Group applications for team-esyfo
> Add access for syfo-oppfolgingsplan-backend
